// -------------------------------------------------------------
// 
// File Name: hdlsrc\First_order_DiscreteTime_DeltaSigma_Modulator_516\CIC_Decimation.v
// Created: 2026-06-12 04:23:17
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_Decimation
// Source Path: First_order_DiscreteTime_DeltaSigma_Modulator_516/Digital_Decimation_Filter/CIC Decimation
// Hierarchy Level: 1
// Model version: 1.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_Decimation
          (clk,
           reset,
           enb,
           enb_1_128_0,
           enb_1_128_7,
           CIC_Decimation_in,
           CIC_Decimation_out);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_128_0;
  input   enb_1_128_7;
  input   signed [7:0] CIC_Decimation_in;  // int8
  output  signed [35:0] CIC_Decimation_out;  // sfix36


  wire stateControl;
  reg  [5:0] delayMatch3_reg;  // ufix1 [6]
  wire stateControl_1;
  wire stateControl_2;
  reg  [5:0] delayMatch2_reg;  // ufix1 [6]
  wire stateControl_3;
  wire stateControl_4;
  reg  [5:0] delayMatch1_reg;  // ufix1 [6]
  wire stateControl_5;
  wire stateControl_7;
  reg  [5:0] delayMatch_reg;  // ufix1 [6]
  wire stateControl_8;
  wire signed [35:0] IS_Section_1_in_DTC;  // sfix36
  reg signed [35:0] IS_Section_1_delay;  // sfix36
  wire signed [35:0] IS_Section_1_out;  // sfix36
  wire signed [35:0] IS_Section_1_out_1;  // sfix36
  reg signed [35:0] IS_Section_2_delay;  // sfix36
  wire signed [35:0] IS_Section_2_out;  // sfix36
  wire signed [35:0] IS_Section_2_out_1;  // sfix36
  reg signed [35:0] IS_Section_3_delay;  // sfix36
  wire signed [35:0] IS_Section_3_out;  // sfix36
  wire signed [35:0] IS_Section_3_out_1;  // sfix36
  reg signed [35:0] IS_Section_4_delay;  // sfix36
  wire signed [35:0] IS_Section_4_out;  // sfix36
  wire signed [35:0] IS_Section_4_out_1;  // sfix36
  reg signed [35:0] downsample_ds_out;  // sfix36
  reg signed [35:0] rateOut;  // sfix36
  reg signed [35:0] CS_Section_1_delay;  // sfix36
  wire signed [35:0] CS_Section_1_out;  // sfix36
  reg signed [35:0] CS_Section_2_delay;  // sfix36
  wire signed [35:0] CS_Section_2_out;  // sfix36
  reg signed [35:0] CS_Section_3_delay;  // sfix36
  wire signed [35:0] CS_Section_3_out;  // sfix36
  reg signed [35:0] CS_Section_4_delay;  // sfix36
  wire signed [35:0] CS_Section_4_out;  // sfix36


  assign stateControl = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        delayMatch3_reg <= {6{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch3_reg[0] <= stateControl;
          delayMatch3_reg[32'sd5:32'sd1] <= delayMatch3_reg[32'sd4:32'sd0];
        end
      end
    end

  assign stateControl_1 = delayMatch3_reg[5];

  assign stateControl_2 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        delayMatch2_reg <= {6{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch2_reg[0] <= stateControl_2;
          delayMatch2_reg[32'sd5:32'sd1] <= delayMatch2_reg[32'sd4:32'sd0];
        end
      end
    end

  assign stateControl_3 = delayMatch2_reg[5];

  assign stateControl_4 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {6{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= stateControl_4;
          delayMatch1_reg[32'sd5:32'sd1] <= delayMatch1_reg[32'sd4:32'sd0];
        end
      end
    end

  assign stateControl_5 = delayMatch1_reg[5];

  assign stateControl_7 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {6{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= stateControl_7;
          delayMatch_reg[32'sd5:32'sd1] <= delayMatch_reg[32'sd4:32'sd0];
        end
      end
    end

  assign stateControl_8 = delayMatch_reg[5];

  assign IS_Section_1_in_DTC = {{28{CIC_Decimation_in[7]}}, CIC_Decimation_in};

  assign IS_Section_1_out = IS_Section_1_in_DTC + IS_Section_1_delay;

  assign IS_Section_1_out_1 = (stateControl_8 == 1'b0 ? IS_Section_1_delay :
              IS_Section_1_out);

  always @(posedge clk or posedge reset)
    begin : IS_Section_delay_process
      if (reset == 1'b1) begin
        IS_Section_1_delay <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          IS_Section_1_delay <= IS_Section_1_out_1;
        end
      end
    end

  assign IS_Section_2_out = IS_Section_1_delay + IS_Section_2_delay;

  assign IS_Section_2_out_1 = (stateControl_5 == 1'b0 ? IS_Section_2_delay :
              IS_Section_2_out);

  always @(posedge clk or posedge reset)
    begin : IS_Section_delay1_process
      if (reset == 1'b1) begin
        IS_Section_2_delay <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          IS_Section_2_delay <= IS_Section_2_out_1;
        end
      end
    end

  assign IS_Section_3_out = IS_Section_2_delay + IS_Section_3_delay;

  assign IS_Section_3_out_1 = (stateControl_3 == 1'b0 ? IS_Section_3_delay :
              IS_Section_3_out);

  always @(posedge clk or posedge reset)
    begin : IS_Section_delay2_process
      if (reset == 1'b1) begin
        IS_Section_3_delay <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          IS_Section_3_delay <= IS_Section_3_out_1;
        end
      end
    end

  assign IS_Section_4_out = IS_Section_3_delay + IS_Section_4_delay;

  assign IS_Section_4_out_1 = (stateControl_1 == 1'b0 ? IS_Section_4_delay :
              IS_Section_4_out);

  always @(posedge clk or posedge reset)
    begin : IS_Section_delay3_process
      if (reset == 1'b1) begin
        IS_Section_4_delay <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          IS_Section_4_delay <= IS_Section_4_out_1;
        end
      end
    end

  // Downsample register
  always @(posedge clk or posedge reset)
    begin : downsample_ds_process
      if (reset == 1'b1) begin
        downsample_ds_out <= 36'sh000000000;
      end
      else begin
        if (enb_1_128_7) begin
          downsample_ds_out <= IS_Section_4_delay;
        end
      end
    end

  // Downsample output register
  always @(posedge clk or posedge reset)
    begin : downsample_output_process
      if (reset == 1'b1) begin
        rateOut <= 36'sh000000000;
      end
      else begin
        if (enb_1_128_0) begin
          rateOut <= downsample_ds_out;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayMatch4_process
      if (reset == 1'b1) begin
        CS_Section_1_delay <= 36'sh000000000;
      end
      else begin
        if (enb_1_128_0) begin
          CS_Section_1_delay <= rateOut;
        end
      end
    end

  assign CS_Section_1_out = rateOut - CS_Section_1_delay;

  always @(posedge clk or posedge reset)
    begin : delayMatch5_process
      if (reset == 1'b1) begin
        CS_Section_2_delay <= 36'sh000000000;
      end
      else begin
        if (enb_1_128_0) begin
          CS_Section_2_delay <= CS_Section_1_out;
        end
      end
    end

  assign CS_Section_2_out = CS_Section_1_out - CS_Section_2_delay;

  always @(posedge clk or posedge reset)
    begin : delayMatch6_process
      if (reset == 1'b1) begin
        CS_Section_3_delay <= 36'sh000000000;
      end
      else begin
        if (enb_1_128_0) begin
          CS_Section_3_delay <= CS_Section_2_out;
        end
      end
    end

  assign CS_Section_3_out = CS_Section_2_out - CS_Section_3_delay;

  always @(posedge clk or posedge reset)
    begin : delayMatch7_process
      if (reset == 1'b1) begin
        CS_Section_4_delay <= 36'sh000000000;
      end
      else begin
        if (enb_1_128_0) begin
          CS_Section_4_delay <= CS_Section_3_out;
        end
      end
    end

  assign CS_Section_4_out = CS_Section_3_out - CS_Section_4_delay;

  assign CIC_Decimation_out = CS_Section_4_out;

endmodule  // CIC_Decimation

