// -------------------------------------------------------------
// 
// File Name: hdlsrc\First_order_DiscreteTime_DeltaSigma_Modulator_516\Digital_Decimation_Filter_tc.v
// Created: 2026-06-12 04:23:17
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Digital_Decimation_Filter_tc
// Source Path: Digital_Decimation_Filter_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_128_0 : 128x slower than clk with last phase
// enb_1_128_1 : 128x slower than clk with phase 1
// enb_1_128_7 : 128x slower than clk with phase 7
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Digital_Decimation_Filter_tc
          (clk,
           reset,
           clk_enable,
           enb,
           enb_1_128_0,
           enb_1_128_1,
           enb_1_128_7);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb;
  output  enb_1_128_0;
  output  enb_1_128_1;
  output  enb_1_128_7;


  reg [6:0] count128;  // ufix7
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_128_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_128_1_1;
  wire comp_7_tmp;
  wire phase_7_tmp;
  reg  phase_7;
  wire enb_1_128_7_1;


  assign enb = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 127
  always @(posedge clk or posedge reset)
    begin : counter_128_process
      if (reset == 1'b1) begin
        count128 <= 7'b0000001;
      end
      else begin
        if (clk_enable) begin
          count128 <= count128 + 7'b0000001;
        end
      end
    end

  assign comp_0_tmp = count128 == 7'b1111111;

  assign phase_0_tmp = comp_0_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_process
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end

  assign enb_1_128_0_1 = phase_0 & clk_enable;

  assign enb_1_128_0 = enb_1_128_0_1;

  assign comp_1_tmp = count128 == 7'b0000000;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_1_process
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end

  assign enb_1_128_1_1 = phase_1 & clk_enable;

  assign enb_1_128_1 = enb_1_128_1_1;

  assign comp_7_tmp = count128 == 7'b0000110;

  assign phase_7_tmp = comp_7_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_2_process
      if (reset == 1'b1) begin
        phase_7 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_7 <= phase_7_tmp;
        end
      end
    end

  assign enb_1_128_7_1 = phase_7 & clk_enable;

  assign enb_1_128_7 = enb_1_128_7_1;

endmodule  // Digital_Decimation_Filter_tc

