// -------------------------------------------------------------
// 
// File Name: hdlsrc\First_order_DiscreteTime_DeltaSigma_Modulator_516\Digital_Decimation_Filter.v
// Created: 2026-06-12 04:23:17
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.95313e-06
// Target subsystem base rate: 1.95313e-06
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.00025
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.00025
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Digital_Decimation_Filter
// Source Path: First_order_DiscreteTime_DeltaSigma_Modulator_516/Digital_Decimation_Filter
// Hierarchy Level: 0
// Model version: 1.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Digital_Decimation_Filter
          (clk,
           reset,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [63:0] In1;  // double
  output  ce_out;
  output  signed [35:0] Out1;  // sfix36


  wire enb;
  wire enb_1_128_0;
  wire enb_1_128_7;
  wire enb_1_128_1;
  wire signed [7:0] Data_Type_Conversion_out1;  // int8
  wire signed [35:0] CIC_Decimation_out1;  // sfix36


  Digital_Decimation_Filter_tc u_Digital_Decimation_Filter_tc (.clk(clk),
                                                               .reset(reset),
                                                               .clk_enable(clk_enable),
                                                               .enb(enb),
                                                               .enb_1_128_0(enb_1_128_0),
                                                               .enb_1_128_1(enb_1_128_1),
                                                               .enb_1_128_7(enb_1_128_7)
                                                               );

  nfp_convert_double_to_fixed_8_En0 u_First_order_DiscreteTime_DeltaSigma_Modulator_516_Digital_Decimation_Filter_nfp_convert_double_to_fixed_8_En0 (.clk(clk),
                                                                                                                                                     .reset(reset),
                                                                                                                                                     .enb(enb),
                                                                                                                                                     .nfp_in(In1),  // double
                                                                                                                                                     .nfp_out(Data_Type_Conversion_out1)  // int8
                                                                                                                                                     );

  CIC_Decimation u_CIC_Decimation (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .enb_1_128_0(enb_1_128_0),
                                   .enb_1_128_7(enb_1_128_7),
                                   .CIC_Decimation_in(Data_Type_Conversion_out1),  // int8
                                   .CIC_Decimation_out(CIC_Decimation_out1)  // sfix36
                                   );

  assign Out1 = CIC_Decimation_out1;

  assign ce_out = enb_1_128_1;

endmodule  // Digital_Decimation_Filter

