// -------------------------------------------------------------
// 
// File Name: hdlsrc\First_order_DiscreteTime_DeltaSigma_Modulator_516\Digital_Decimation_Filter_tb.v
// Created: 2026-06-12 04:25:02
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.95313e-06
// Target subsystem base rate: 1.95313e-06
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Digital_Decimation_Filter_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Digital_Decimation_Filter_tb;



  reg  clk;
  reg  reset;
  wire clk_enable;
  wire Out1_done;  // ufix1
  wire ce_out;
  wire Out1_done_enb;  // ufix1
  reg [15:0] Out1_addr;  // ufix16
  wire Out1_active;  // ufix1
  reg [22:0] Sign_out1_addr;  // ufix23
  wire Sign_out1_active;  // ufix1
  reg  tb_enb_delay;
  wire Sign_out1_enb;  // ufix1
  wire [22:0] Sign_out1_addr_delay_1;  // ufix23
  wire tb_enb;
  reg signed [31:0] fp_In1;  // sfix32
  reg  snkDone;
  reg [63:0] rawData_In1;  // ufix64
  reg signed [31:0] status_In1;  // sfix32
  reg [63:0] holdData_In1;  // ufix64
  reg [63:0] In1_offset;  // ufix64
  reg [63:0] In1;  // ufix64
  wire [63:0] In1_1;  // ufix64
  wire snkDonen;
  wire resetn;
  wire notDone;
  wire signed [35:0] Out1;  // sfix36
  wire Out1_enb;  // ufix1
  wire Out1_lastAddr;  // ufix1
  wire constone;  // ufix1
  reg  Out1_chkenb;  // ufix1
  wire Out1_chkdata;  // ufix1
  wire [15:0] Out1_addr_delay_1;  // ufix16
  reg signed [31:0] fp_Out1_expected;  // sfix32
  reg signed [35:0] Out1_expected;  // sfix36
  reg signed [31:0] status_Out1_expected;  // sfix32
  reg signed [35:0] Out1_ref_hold;  // sfix36
  wire signed [35:0] Out1_refTmp;  // sfix36
  wire signed [35:0] Out1_ref;  // sfix36
  reg  Out1_testFailure;  // ufix1
  wire testFailure;  // ufix1

  function real absReal(input real num);
  begin
    if (num < 0)
      absReal = -num;
    else
      absReal = num;
  end
  endfunction

  function real floatHalfToReal;
  input [15:0] x;
  reg [63:0] conv;

  begin
    conv[63] = x[15]; // sign 
    if (x[14:10] == 5'b0) // exp 
      conv[62:52] = 11'b0; 
    else
      conv[62:52] = 1023 + (x[14:10] - 15);
    conv[51:42] = x[9:0]; // mantissa 
    conv[41:0] = 42'b0;
    if (((x[14:10] == 5'h1F) && (x[9:0] != 10'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatHalfToReal = $bitstoreal(conv);
  end
  endfunction

  function real floatSingleToReal;
  input [31:0] x;
  reg [63:0] conv;

  begin
    conv[63] = x[31]; // sign 
    if (x[30:23] == 8'b0) // exp 
      conv[62:52] = 11'b0; 
    else
      conv[62:52] = 1023 + (x[30:23] - 127);
    conv[51:29] = x[22:0]; // mantissa 
    conv[28:0] = 29'b0;
    if (((x[30:23] == 8'hFF) && (x[22:0] != 23'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatSingleToReal = $bitstoreal(conv);
  end
  endfunction

  function real floatDoubleToReal;
  input [63:0] x;
  reg [63:0] conv;

  begin
    conv[63:0] = x[63:0]; 
    if (((x[62:52] == 11'h7FF) && (x[51:0] != 52'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatDoubleToReal = $bitstoreal(conv);
  end
  endfunction

  function isFloatEpsEqual(input real a, input real b, input real eps);
  real absdiff;

  begin
    absdiff = absReal(a - b);
    if (absdiff < eps) // absolute error check 
      isFloatEpsEqual = 1;
    else if (a == b) // check infinities 
      isFloatEpsEqual = 1; 
    else if (a*b == 0.0) // either is zero 
      isFloatEpsEqual = (absdiff < eps);
    else if (absReal(a) < absReal(b)) // relative error check
      isFloatEpsEqual = absdiff/absReal(b) < eps;
    else
      isFloatEpsEqual = absdiff/absReal(a) < eps;
  end
  endfunction
  function isFloatHalfEpsEqual;
  input [15:0] x;
  input [15:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatHalfToReal(x);
    b = floatHalfToReal(y);
    isFloatHalfEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction
  function isFloatSingleEpsEqual;
  input [31:0] x;
  input [31:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatSingleToReal(x);
    b = floatSingleToReal(y);
    isFloatSingleEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction
  function isFloatDoubleEpsEqual;
  input [63:0] x;
  input [63:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatDoubleToReal(x);
    b = floatDoubleToReal(y);
    isFloatDoubleEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction

  assign Out1_done_enb = Out1_done & ce_out;

  assign Out1_active = Out1_addr != 16'b1001110001000000;

  assign Sign_out1_active = Sign_out1_addr != 23'b10011100010000000000000;

  assign Sign_out1_enb = Sign_out1_active & (tb_enb_delay & tb_enb_delay);

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 5120000
  always @(posedge clk or posedge reset)
    begin : Sign_process
      if (reset == 1'b1) begin
        Sign_out1_addr <= 23'b00000000000000000000000;
      end
      else begin
        if (Sign_out1_enb) begin
          if (Sign_out1_addr >= 23'b10011100010000000000000) begin
            Sign_out1_addr <= 23'b00000000000000000000000;
          end
          else begin
            Sign_out1_addr <= Sign_out1_addr + 23'b00000000000000000000001;
          end
        end
      end
    end

  assign #1 Sign_out1_addr_delay_1 = Sign_out1_addr;

  // Data source for In1
  initial
    begin : In1_fileread
      fp_In1 = $fopen("In1.dat", "r");
      status_In1 = $rewind(fp_In1);
    end

  always @(Sign_out1_addr_delay_1, tb_enb_delay, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_In1 <= 64'bx;
        if (snkDone == 1) begin
          $fclose(fp_In1);
        end
      end
      else if (tb_enb_delay == 1) begin
        status_In1 = $fscanf(fp_In1, "%h", rawData_In1);
      end
    end

  // holdData reg for Sign_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Sign_out1
      if (reset) begin
        holdData_In1 <= 64'bx;
      end
      else begin
        holdData_In1 <= rawData_In1;
      end
    end

  always @(rawData_In1 or tb_enb_delay)
    begin : stimuli_Sign_out1_1
      if (tb_enb_delay == 1'b0) begin
        In1_offset <= holdData_In1;
      end
      else begin
        In1_offset <= rawData_In1;
      end
    end

  always #2 In1 <= In1_offset;

  assign In1_1 = In1;

  assign snkDonen =  ~ snkDone;

  assign resetn =  ~ reset;

  assign tb_enb = resetn & snkDonen;

  // Delay inside enable generation: register depth 1
  always @(posedge clk or posedge reset)
    begin : u_enable_delay_process
      if (reset == 1'b1) begin
        tb_enb_delay <= 1'b0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign notDone = tb_enb_delay & snkDonen;

  assign #2 clk_enable = notDone;

  initial
    begin : reset_gen
      $dumpfile("filter_waves.vcd");
      $dumpvars(0, Digital_Decimation_Filter_tb);
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (snkDone == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  Digital_Decimation_Filter u_Digital_Decimation_Filter (.clk(clk),
                                                         .reset(reset),
                                                         .clk_enable(clk_enable),
                                                         .In1(In1_1),  // double
                                                         .ce_out(ce_out),
                                                         .Out1(Out1)  // sfix36
                                                         );

  assign Out1_enb = ce_out & Out1_active;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 40000
  always @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        Out1_addr <= 16'b0000000000000000;
      end
      else begin
        if (Out1_enb) begin
          if (Out1_addr >= 16'b1001110001000000) begin
            Out1_addr <= 16'b0000000000000000;
          end
          else begin
            Out1_addr <= Out1_addr + 16'b0000000000000001;
          end
        end
      end
    end

  assign Out1_lastAddr = Out1_addr >= 16'b1001110001000000;

  assign Out1_done = Out1_lastAddr & resetn;

  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        snkDone <= 0;
      end
      else begin
        if (Out1_done_enb) begin
          snkDone <= Out1_done;
        end
      end
    end

  assign constone = 1'b1;

  // Delay to implement IgnoreDataChecking
  always @(posedge clk or posedge reset)
    begin : Out1_IgnoreDataChecking
      if (reset) begin
        Out1_chkenb <= 0;
      end
      else begin
        if (ce_out) begin
          Out1_chkenb <= constone;
        end
      end
    end

  assign Out1_chkdata = ce_out & Out1_chkenb;

  assign #1 Out1_addr_delay_1 = Out1_addr;

  // Data source for Out1_expected
  initial
    begin : Out1_expected_fileread
      fp_Out1_expected = $fopen("Out1_expected.dat", "r");
      status_Out1_expected = $rewind(fp_Out1_expected);
    end

  always @(Out1_addr_delay_1,  tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        Out1_expected <= 36'bx;
        if (snkDone == 1) begin
          $fclose(fp_Out1_expected);
        end
      end
      else  begin
        status_Out1_expected = $fscanf(fp_Out1_expected, "%h", Out1_expected);
      end
    end

  // Bypass register to hold Out1_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Out1_ref
      if (reset) begin
        Out1_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Out1_ref_hold <= Out1_expected;
        end
      end
    end

  assign Out1_refTmp = Out1_expected;

  assign Out1_ref = (ce_out == 1'b0 ? Out1_ref_hold :
              Out1_refTmp);

  always @(posedge clk or posedge reset)
    begin : Out1_checker
      if (reset == 1'b1) begin
        Out1_testFailure <= 1'b0;
      end
      else begin
        if (Out1_chkdata == 1'b1 && Out1 !== Out1_ref) begin
          Out1_testFailure <= 1'b1;
          $display("ERROR in Out1 at time %t : Expected '%h' Actual '%h'", $time, Out1_ref, Out1);
        end
      end
    end

  assign testFailure = Out1_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (snkDone == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // Digital_Decimation_Filter_tb

